apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nzihm4b2x-nodejs 
  janus-idp.io/tekton: nzihm4b2x-nodejs
  backstage.io/kubernetes-id: nzihm4b2x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nzihm4b2x-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml