apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nzihm4b2x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nzihm4b2x-nodejs 
  name: nzihm4b2x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nzihm4b2x-nodejs 
